"""Compare IDP extraction against MuleSoft data from Salesforce.

Produces a list of structured Findings + a confidence score for the case.
Pure logic — no Salesforce calls, no I/O. Takes two dicts in, returns a result.
"""
import logging
from dataclasses import dataclass, field
from difflib import SequenceMatcher
from typing import Any

logger = logging.getLogger(__name__)


# Finding categories
DUPLICATE_MEMBER = "DUPLICATE_MEMBER"
DUPLICATE_INCOME = "DUPLICATE_INCOME"
DUPLICATE_ASSET = "DUPLICATE_ASSET"
MISSING_MEMBER = "MISSING_MEMBER"     # AI found, MuleSoft missed
MISSING_INCOME = "MISSING_INCOME"     # AI found, MuleSoft missed
MISSING_ASSET = "MISSING_ASSET"       # AI found, MuleSoft missed
IDP_MISSED_MEMBER = "IDP_MISSED_MEMBER"   # MuleSoft has, AI missed
IDP_MISSED_INCOME = "IDP_MISSED_INCOME"
IDP_MISSED_ASSET = "IDP_MISSED_ASSET"
VALUE_MISMATCH = "VALUE_MISMATCH"
COMPLIANCE = "COMPLIANCE"
# IDP-internal findings (not from comparison) — generated by the pipeline
# from cross-doc validation, special scenarios, bug detection, cert type
# rules, and field-level scoring.
INTERNAL_DISCREPANCY = "INTERNAL_DISCREPANCY"  # income/asset mismatches within the file
FIELD_QUALITY = "FIELD_QUALITY"                # [RED]/[YELLOW] field-level scoring findings
EXTRACTION_NOTE = "EXTRACTION_NOTE"            # workflow notes (pages excluded, name variants)


@dataclass
class Finding:
    category: str
    severity: str    # "high" | "medium" | "low" | "info"
    message: str
    detail: dict[str, Any] = field(default_factory=dict)


@dataclass
class Confidence:
    extraction_score: float
    agreement_rate: float
    case_confidence: float
    flag: str    # "green" | "yellow" | "red"
    agreements: int
    disagreements: int
    ai_only_records: int
    sf_only_records: int


@dataclass
class ComparisonResult:
    findings: list[Finding]
    confidence: Confidence


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ssn_last4(ssn: str | None) -> str:
    if not ssn:
        return ""
    return str(ssn).replace("-", "").replace("*", "")[-4:]


def _norm(s: str | None) -> str:
    return (s or "").strip().lower()


def _money(v: Any) -> float | None:
    if v is None or v == "":
        return None
    try:
        return float(str(v).replace(",", "").replace("$", "").strip())
    except (ValueError, TypeError):
        return None


def _close(a: float, b: float, tolerance: float = 0.05) -> bool:
    if a == 0 and b == 0:
        return True
    if a == 0 or b == 0:
        return False
    return abs(a - b) / max(abs(a), abs(b)) < tolerance


# ---------------------------------------------------------------------------
# Synonym tables — map AI extraction names to MuleSoft's abbreviations.
# Both sides get normalized to a canonical form before comparison.
# Maps to either an explicit canonical or a longer matching string.
# ---------------------------------------------------------------------------

_INCOME_SOURCE_SYNONYMS: dict[str, str] = {
    # Social Security family
    "ssa": "social security administration",
    "ss": "social security administration",
    "social security": "social security administration",
    "social security administration": "social security administration",
    # SSI
    "ssi": "supplemental security income",
    "supplemental security income": "supplemental security income",
    # SSDI
    "ssdi": "social security disability",
    "social security disability": "social security disability",
    # State supplements (varies by state — group together)
    "ssp": "state supplement program",
    "state supplement program": "state supplement program",
    "massachusetts state supplement program": "state supplement program",
    "ma ssp": "state supplement program",
    "ma state supplement": "state supplement program",
    # Public assistance
    "tanf": "temporary assistance",
    "temporary assistance": "temporary assistance",
    "calworks": "temporary assistance",
    "colorado works program": "temporary assistance",
    "colorado works": "temporary assistance",
    "afdc": "temporary assistance",
    # Anticipated income — MuleSoft sometimes uses this as a generic
    # bucket; treat as "self-declared" so it can match AI's TIC extraction.
    "anticipated income": "self-declared",
    "self-declared": "self-declared",
    "self declared": "self-declared",
}


def _normalize_income_source(name: str | None) -> str:
    """Map an income source name to its canonical form for comparison."""
    raw = _norm(name)
    if not raw:
        return ""
    if raw in _INCOME_SOURCE_SYNONYMS:
        return _INCOME_SOURCE_SYNONYMS[raw]
    # Substring fallback — handle "Massachusetts SSP", "MA SSI", etc.
    for synonym, canonical in _INCOME_SOURCE_SYNONYMS.items():
        if synonym in raw or raw in synonym:
            return canonical
    return raw


# Common organizational suffixes/prefixes — stripped before fuzzy matching
# so "Coherent Corp" matches "Coherent", "The Walt Disney Company" matches
# "Walt Disney Company", etc.
_ORG_SUFFIXES = {
    "corp", "corporation", "inc", "incorporated", "llc", "l.l.c",
    "ltd", "limited", "co", "company", "lp", "l.p", "llp",
    "plc", "pllc", "pc", "p.c", "group", "holdings",
}
_ORG_PREFIXES = {"the", "a", "an"}


def _normalize_org_name(name: str | None) -> str:
    """Strip common corporate suffixes/prefixes for fuzzy comparison.

    Examples:
      'Coherent Corp'             → 'coherent'
      'The Walt Disney Company'   → 'walt disney'
      'B&T Building Services Inc' → 'b&t building services'
      'XYZ, LLC.'                 → 'xyz'
    """
    raw = _norm(name)
    if not raw:
        return ""
    # Strip punctuation that commonly appears in business names
    cleaned = raw.replace(",", " ").replace(".", " ").replace("'", "")
    tokens = [t for t in cleaned.split() if t]
    # Drop trailing org suffixes
    while tokens and tokens[-1] in _ORG_SUFFIXES:
        tokens.pop()
    # Drop leading articles
    while tokens and tokens[0] in _ORG_PREFIXES:
        tokens.pop(0)
    return " ".join(tokens) if tokens else raw


def _name_similarity(a: str, b: str) -> float:
    """Best-of full-string and per-token similarity.

    Full-string ratio handles "Walt Disney Company" vs "The Walt Disney
    Company" cleanly. But OCR errors like "chilts" vs "chilis bar & grill"
    fail the full-string check (extra tokens drag the ratio down). Per-
    token best-pair similarity catches those.
    """
    if not a or not b:
        return 0.0
    full_ratio = SequenceMatcher(None, a, b).ratio()

    # Per-token best pair: split both, find the best matching pair.
    a_tokens = [t for t in a.split() if len(t) > 2]
    b_tokens = [t for t in b.split() if len(t) > 2]
    best_token = 0.0
    for ta in a_tokens:
        for tb in b_tokens:
            r = SequenceMatcher(None, ta, tb).ratio()
            if r > best_token:
                best_token = r

    return max(full_ratio, best_token)


def _normalize_account_type(t: str | None) -> str:
    """Strip variants of 'Account' suffix so 'Checking' matches 'Checking Account'.

    Also collapses some common synonyms:
      'investment account', 'stocks', 'brokerage' → 'investment'
      '401k', 'ira', 'retirement account'         → 'retirement'
    """
    raw = _norm(t)
    if not raw:
        return ""
    # Strip trailing " account" / " acct" / leading "personal "
    for suffix in (" account", " acct", " accts"):
        if raw.endswith(suffix):
            raw = raw[: -len(suffix)].strip()
    if raw.startswith("personal "):
        raw = raw[len("personal "):].strip()
    # Common synonyms
    synonyms = {
        "stocks": "investment",
        "brokerage": "investment",
        "investment account": "investment",
        "401k": "retirement",
        "ira": "retirement",
        "roth ira": "retirement",
        "money market": "savings",
        "cd": "savings",
        "certificate of deposit": "savings",
    }
    return synonyms.get(raw, raw)


def _account_types_compatible(a: str | None, b: str | None) -> bool:
    """Loose accountType match — allows 'Checking' ≈ 'Checking Account'."""
    na = _normalize_account_type(a)
    nb = _normalize_account_type(b)
    if not na or not nb:
        return True   # one side missing — don't block on type
    return na == nb


# ---------------------------------------------------------------------------
# Member comparison
# ---------------------------------------------------------------------------

def _member_key(rec: dict) -> tuple[str, str]:
    """Strict identity key: (DOB, last 4 of SSN)."""
    dob = rec.get("DOB") or rec.get("DOB__c") or ""
    # Salesforce sometimes returns dates as ISO datetime strings; normalize to date-only.
    dob_str = str(dob)[:10] if dob else ""
    return (
        dob_str,
        _ssn_last4(rec.get("socialSecurityNumber") or rec.get("SSN__c")),
    )


def _member_name_key(rec: dict) -> str:
    """Fallback key based on name — used when DOB/SSN are partial."""
    first = (rec.get("FirstName") or rec.get("First_Name__c") or "").strip().lower()
    last = (rec.get("LastName") or rec.get("Last_Name__c") or "").strip().lower()
    return f"{first} {last}".strip()


def _compare_members(ai_members: list[dict], sf_members: list[dict]) -> tuple[list[Finding], dict]:
    findings: list[Finding] = []

    # SF dedup: warn on duplicates within SF
    sf_keys: dict[tuple, list[dict]] = {}
    for m in sf_members:
        k = _member_key(m)
        sf_keys.setdefault(k, []).append(m)

    for k, group in sf_keys.items():
        if len(group) > 1 and k != ("", ""):
            name = f"{group[0].get('First_Name__c', '')} {group[0].get('Last_Name__c', '')}".strip()
            findings.append(Finding(
                category=DUPLICATE_MEMBER,
                severity="high",
                message=f"DUPLICATE MEMBER — {name} appears {len(group)} times in MuleSoft",
                detail={"key": list(k), "count": len(group)},
            ))

    ai_keys = {_member_key(m): m for m in ai_members if _member_key(m) != ("", "")}
    sf_keys_set = {k for k in sf_keys if k != ("", "")}

    matched = ai_keys.keys() & sf_keys_set
    ai_only_keys = ai_keys.keys() - sf_keys_set
    sf_only_keys = sf_keys_set - ai_keys.keys()

    # Name-based fuzzy fallback: if a member's strict (DOB, SSN) key
    # doesn't match across systems but their NAMES are similar (e.g.,
    # "Yvet Belen" vs "Yvett Belen" — single-letter OCR variant), treat
    # as matched and surface a low-severity mismatch finding instead of
    # flagging both directions as missing.
    ai_only_with_names = [
        (_member_name_key(ai_keys[k]), k) for k in ai_only_keys
    ]
    sf_only_with_names = [
        (_member_name_key(sf_keys[k][0]), k) for k in sf_only_keys
    ]

    fallback_matched_ai_keys: set[tuple[str, str]] = set()
    fallback_matched_sf_keys: set[tuple[str, str]] = set()
    fuzzy_match_pairs: list[tuple[str, str]] = []

    for ai_name, ai_k in ai_only_with_names:
        if not ai_name:
            continue
        best_ratio = 0.0
        best_sf_key: tuple[str, str] | None = None
        best_sf_name: str = ""
        for sf_name, sf_k in sf_only_with_names:
            if not sf_name or sf_k in fallback_matched_sf_keys:
                continue
            # 0.82 threshold catches single-letter OCR variants like
            # "Latisha" / "Latticia" (ratio 0.83) and "Yvet" / "Yvett"
            # (ratio 0.95). Tighter would miss those; looser risks
            # false-matching distinct names.
            ratio = _name_similarity(ai_name, sf_name)
            if ratio > best_ratio:
                best_ratio = ratio
                best_sf_key = sf_k
                best_sf_name = sf_name
        if best_ratio >= 0.82 and best_sf_key is not None:
            fallback_matched_ai_keys.add(ai_k)
            fallback_matched_sf_keys.add(best_sf_key)
            fuzzy_match_pairs.append((ai_name, best_sf_name))

    ai_only = ai_only_keys - fallback_matched_ai_keys
    sf_only = sf_only_keys - fallback_matched_sf_keys

    # Surface the fuzzy matches as a single low-severity finding per pair
    for ai_name, sf_name in fuzzy_match_pairs:
        if ai_name == sf_name:
            msg = (
                f"Member identity mismatch — '{ai_name.title()}' exists in "
                f"both systems but DOB/SSN keys differ"
            )
        else:
            msg = (
                f"Name spelling variant — AI: '{ai_name.title()}' vs "
                f"MuleSoft: '{sf_name.title()}' (likely same person)"
            )
        findings.append(Finding(
            category=VALUE_MISMATCH,
            severity="low",
            message=msg,
        ))

    for k in ai_only:
        m = ai_keys[k]
        name = f"{m.get('FirstName', '')} {m.get('LastName', '')}".strip()
        findings.append(Finding(
            category=MISSING_MEMBER,
            severity="high",
            message=(
                f"MuleSoft missing household member — {name} "
                f"(DOB: {m.get('DOB')}, SSN: ***-**-{k[1]})"
            ),
            detail={"name": name, "dob": m.get("DOB"), "ssn4": k[1]},
        ))

    for k in sf_only:
        m = sf_keys[k][0]
        name = f"{m.get('First_Name__c', '')} {m.get('Last_Name__c', '')}".strip()
        findings.append(Finding(
            category=IDP_MISSED_MEMBER,
            severity="medium",
            message=(
                f"AI may have missed household member — {name} "
                f"is in MuleSoft but not in AI extraction"
            ),
            detail={"name": name, "ssn4": k[1]},
        ))

    # Value mismatch on matched members (Disabled / Student)
    for k in matched:
        ai_m = ai_keys[k]
        sf_m = sf_keys[k][0]
        ai_dis = _norm(ai_m.get("disabled"))
        sf_dis = "y" if sf_m.get("Disabled__c") else "n" if sf_m.get("Disabled__c") is False else ""
        if ai_dis and sf_dis and ai_dis != sf_dis:
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity="medium",
                message=(
                    f"Disability mismatch — {ai_m.get('FirstName')} {ai_m.get('LastName')}: "
                    f"AI={ai_dis} MuleSoft={sf_dis}"
                ),
            ))

    return findings, {
        "agreements": len(matched),
        "disagreements": 0,
        "ai_only": len(ai_only),
        "sf_only": len(sf_only),
    }


# ---------------------------------------------------------------------------
# Income comparison
# ---------------------------------------------------------------------------

def _income_key(rec: dict) -> tuple[str, str]:
    """Source name (normalized through synonym table) + member name.

    AI extracts full names ('social security administration'), MuleSoft
    often uses abbreviations ('ssa'). Both go through the same synonym
    map so they match correctly.
    """
    source = rec.get("sourceName") or rec.get("Source_Name__c")
    member = rec.get("memberName") or rec.get("House_Member_Name__c") or ""
    # Normalize member: trim middle initial / 'r.' / 'jr' suffixes for fuzzy match.
    member_clean = _norm(member).replace(".", "").strip()
    member_tokens = [t for t in member_clean.split() if len(t) > 1]
    member_key = " ".join(member_tokens) if member_tokens else member_clean
    return (_normalize_income_source(source), member_key)


def _compare_income(
    ai_income: list[dict], ai_calculations: list[dict], sf_income: list[dict],
) -> tuple[list[Finding], dict]:
    findings: list[Finding] = []

    # Build map of AI annual amounts by source
    ai_annual: dict[tuple[str, str], float] = {}
    for calc in ai_calculations or []:
        k = (_norm(calc.get("sourceName")), _norm(calc.get("memberName")))
        amt = _money(calc.get("annualIncome"))
        if amt is not None:
            ai_annual[k] = amt

    # SF dedup check
    sf_keys: dict[tuple, list[dict]] = {}
    for inc in sf_income:
        k = _income_key(inc)
        sf_keys.setdefault(k, []).append(inc)

    # Detect SF duplicates within the same canonical source name
    for k, group in sf_keys.items():
        if len(group) > 1 and k[0]:
            findings.append(Finding(
                category=DUPLICATE_INCOME,
                severity="high",
                message=(
                    f"DUPLICATE INCOME — '{group[0].get('Source_Name__c')}' "
                    f"appears {len(group)} times in MuleSoft for the same member"
                ),
            ))

    ai_keys = set(_income_key(r) for r in ai_income)
    matched = ai_keys & set(sf_keys.keys())
    ai_only_keys = ai_keys - set(sf_keys.keys())
    sf_only_keys = set(sf_keys.keys()) - ai_keys

    # Fuzzy-match remaining AI-only and SF-only sources by name similarity.
    # Catches employer name variants like:
    #   "b&t building services" (AI) vs "b&t services inc." (SF)
    #   "ABC Staffing LLC" (AI)   vs "ABC Staffing"        (SF)
    # Same threshold (0.85) as member fuzzy matching.
    fuzzy_matched_ai: set[tuple[str, str]] = set()
    fuzzy_matched_sf: set[tuple[str, str]] = set()
    fuzzy_pairs: list[tuple[tuple[str, str], tuple[str, str]]] = []

    sf_only_list = list(sf_only_keys)
    for ai_k in ai_only_keys:
        if not ai_k[0]:    # skip empty source names
            continue
        ai_normalized = _normalize_org_name(ai_k[0])
        best_ratio = 0.0
        best_sf_k: tuple[str, str] | None = None
        for sf_k in sf_only_list:
            if sf_k in fuzzy_matched_sf or not sf_k[0]:
                continue
            # Match by source name similarity AND same member (or empty member).
            # If both have member names, they must also fuzzy-match.
            if ai_k[1] and sf_k[1]:
                member_ratio = SequenceMatcher(None, ai_k[1], sf_k[1]).ratio()
                if member_ratio < 0.7:
                    continue
            sf_normalized = _normalize_org_name(sf_k[0])
            # Strip corporate suffixes/prefixes AND check per-token
            # similarity — catches "Coherent Corp" ↔ "Coherent",
            # "The Walt Disney Company" ↔ "Walt Disney Company",
            # AND "chilts" ↔ "chilis bar & grill" (per-token: chilts/chilis).
            source_ratio = _name_similarity(ai_normalized, sf_normalized)
            if source_ratio > best_ratio:
                best_ratio = source_ratio
                best_sf_k = sf_k
        if best_ratio >= 0.85 and best_sf_k is not None:
            fuzzy_matched_ai.add(ai_k)
            fuzzy_matched_sf.add(best_sf_k)
            fuzzy_pairs.append((ai_k, best_sf_k))

    ai_only = ai_only_keys - fuzzy_matched_ai
    sf_only = sf_only_keys - fuzzy_matched_sf

    agreements = 0
    disagreements = 0

    for k in matched:
        ai_amt = ai_annual.get(k)
        sf_amt = _money(sf_keys[k][0].get("Gross_Member_Income__c"))
        if ai_amt is not None and sf_amt is not None and sf_amt > 0:
            if _close(ai_amt, sf_amt, tolerance=0.01):
                agreements += 1
            else:
                disagreements += 1
                findings.append(Finding(
                    category=VALUE_MISMATCH,
                    severity="medium",
                    message=(
                        f"INCOME MISMATCH — {sf_keys[k][0].get('Source_Name__c')}: "
                        f"AI ${ai_amt:,.2f} vs MuleSoft ${sf_amt:,.2f}"
                    ),
                    detail={
                        "source": sf_keys[k][0].get("Source_Name__c"),
                        "ai_amount": ai_amt,
                        "sf_amount": sf_amt,
                    },
                ))
        else:
            agreements += 1     # both present, can't compare values

    # Surface fuzzy-matched income sources as low-severity name variants.
    # Treat as agreements for confidence scoring (both systems have it).
    for ai_k, sf_k in fuzzy_pairs:
        agreements += 1
        findings.append(Finding(
            category=VALUE_MISMATCH,
            severity="low",
            message=(
                f"Income source name variant — AI: '{ai_k[0]}' vs "
                f"MuleSoft: '{sf_k[0]}' (likely same source)"
            ),
        ))

    for k in ai_only:
        findings.append(Finding(
            category=MISSING_INCOME,
            severity="high",
            message=f"MuleSoft missing income source — '{k[0]}' for {k[1] or 'household'}",
        ))

    for k in sf_only:
        findings.append(Finding(
            category=IDP_MISSED_INCOME,
            severity="medium",
            message=f"AI may have missed income source — '{k[0]}' is in MuleSoft",
        ))

    return findings, {
        "agreements": agreements,
        "disagreements": disagreements,
        "ai_only": len(ai_only),
        "sf_only": len(sf_only),
    }


# ---------------------------------------------------------------------------
# Asset comparison
# ---------------------------------------------------------------------------

def _asset_key(rec: dict) -> tuple[str, str, str]:
    """sourceName + accountType + last 4 of accountNumber."""
    src = _norm(rec.get("sourceName") or rec.get("Source_Name__c"))
    acct_type = _norm(rec.get("accountType") or rec.get("Account_Type__c"))
    acct_num = str(rec.get("accountNumber") or "").strip()
    if not acct_num:
        # Fall back to a balance-based stub for SF records without account #
        bal = (rec.get("Cash_Value__c") or rec.get("VOA_Current__c") or
               rec.get("currentBalance") or "")
        acct_num = f"~{bal}"
    last4 = acct_num[-4:].lower() if len(acct_num) >= 4 else acct_num.lower()
    return (src, acct_type, last4)


def _compare_assets(
    ai_assets: list[dict], sf_assets: list[dict],
) -> tuple[list[Finding], dict]:
    findings: list[Finding] = []

    # Filter out SF asset records with no identifying fields — they're
    # placeholder rows MuleSoft sometimes creates that we can't compare
    # meaningfully. (Examples: real-estate stubs with no source/account.)
    sf_assets_filtered: list[dict] = []
    sf_orphan_count = 0
    for a in sf_assets:
        has_source = bool((a.get("Source_Name__c") or "").strip())
        has_account = bool((a.get("accountNumber") or "").strip())
        has_balance = _money(a.get("Cash_Value__c") or a.get("VOA_Current__c"))
        if not has_source and not has_account and not has_balance:
            sf_orphan_count += 1
            continue
        sf_assets_filtered.append(a)

    if sf_orphan_count > 0:
        logger.debug(
            "Filtered %d MuleSoft asset record(s) with no identifying fields",
            sf_orphan_count,
        )

    sf_keys: dict[tuple, list[dict]] = {}
    for a in sf_assets_filtered:
        k = _asset_key(a)
        sf_keys.setdefault(k, []).append(a)

    for k, group in sf_keys.items():
        if len(group) > 1:
            findings.append(Finding(
                category=DUPLICATE_ASSET,
                severity="high",
                message=(
                    f"DUPLICATE ASSET — '{group[0].get('Source_Name__c')}' "
                    f"({group[0].get('Account_Type__c')}) appears {len(group)} times"
                ),
            ))

    ai_keys = {_asset_key(a): a for a in ai_assets}
    matched = ai_keys.keys() & set(sf_keys.keys())
    ai_only_keys = ai_keys.keys() - set(sf_keys.keys())
    sf_only_keys = set(sf_keys.keys()) - ai_keys.keys()

    # Fuzzy-match remaining assets by sourceName similarity + same accountType
    # + close balance. Catches variants like:
    #   "Knights Of Columbus" (AI) vs "4633 KOC" (MuleSoft)
    #   "The Walt Disney Company" (AI) vs "Walt Disney Company" (MuleSoft)
    fuzzy_matched_ai_assets: set[tuple] = set()
    fuzzy_matched_sf_assets: set[tuple] = set()
    asset_fuzzy_pairs: list[tuple[tuple, tuple]] = []

    sf_only_list = list(sf_only_keys)
    for ai_k in ai_only_keys:
        ai_rec = ai_keys[ai_k]
        ai_src_norm = _normalize_org_name(ai_k[0])
        ai_type = ai_k[1]
        ai_bal = _money(ai_rec.get("currentBalance"))
        if not ai_src_norm and ai_bal is None:
            continue   # nothing to fuzzy-match on

        best_score = 0.0
        best_sf_k: tuple | None = None
        for sf_k in sf_only_list:
            if sf_k in fuzzy_matched_sf_assets:
                continue
            # accountType must be compatible after normalization
            # ('Checking' ≈ 'Checking Account', 'Investment' ≈ 'Brokerage').
            if not _account_types_compatible(ai_type, sf_k[1]):
                continue
            sf_rec = sf_keys[sf_k][0]
            sf_src_norm = _normalize_org_name(sf_k[0])
            sf_bal = _money(
                sf_rec.get("Cash_Value__c") or sf_rec.get("VOA_Current__c")
            )

            # Score = combination of name similarity and balance match.
            # Use _name_similarity (full-string + per-token) to catch
            # "Knights of Columbus" ↔ "4633 KOC" via balance, and
            # "Walt Disney" ↔ "The Walt Disney Company" via tokens.
            name_score = 0.0
            if ai_src_norm and sf_src_norm:
                name_score = _name_similarity(ai_src_norm, sf_src_norm)
            balance_match = (
                ai_bal is not None and sf_bal is not None
                and _close(ai_bal, sf_bal, tolerance=0.02)
            )

            # Near-perfect name match: same asset regardless of balance.
            # MuleSoft sometimes leaves Cash_Value__c as 0 or null even
            # when AI extracted a real balance from the PDF — surface as
            # a value mismatch rather than two missing/missed entries.
            if name_score >= 0.95:
                if name_score > best_score:
                    best_score = name_score
                    best_sf_k = sf_k
                    continue
            # Strong match: balance matches AND (name similar OR one source is empty)
            if balance_match and (name_score >= 0.85 or not ai_src_norm or not sf_src_norm):
                if name_score > best_score:
                    best_score = max(name_score, 0.86)
                    best_sf_k = sf_k
            # Moderate match: name very similar AND no balance contradiction
            elif name_score >= 0.85 and (ai_bal is None or sf_bal is None or balance_match):
                if name_score > best_score:
                    best_score = name_score
                    best_sf_k = sf_k

        if best_score >= 0.85 and best_sf_k is not None:
            fuzzy_matched_ai_assets.add(ai_k)
            fuzzy_matched_sf_assets.add(best_sf_k)
            asset_fuzzy_pairs.append((ai_k, best_sf_k))

    ai_only = ai_only_keys - fuzzy_matched_ai_assets
    sf_only = sf_only_keys - fuzzy_matched_sf_assets

    agreements = 0
    disagreements = 0

    for k in matched:
        ai_bal = _money(ai_keys[k].get("currentBalance"))
        sf_bal = _money(sf_keys[k][0].get("Cash_Value__c") or
                        sf_keys[k][0].get("VOA_Current__c"))
        if ai_bal is not None and sf_bal is not None:
            if _close(ai_bal, sf_bal, tolerance=0.02):
                agreements += 1
            else:
                disagreements += 1
                findings.append(Finding(
                    category=VALUE_MISMATCH,
                    severity="medium",
                    message=(
                        f"ASSET BALANCE MISMATCH — "
                        f"{sf_keys[k][0].get('Source_Name__c')} "
                        f"{sf_keys[k][0].get('Account_Type__c')}: "
                        f"AI ${ai_bal:,.2f} vs MuleSoft ${sf_bal:,.2f}"
                    ),
                ))
        else:
            agreements += 1

    # Surface fuzzy-matched assets as low-severity name variants.
    # Treat as agreements for confidence scoring. Also flag if the
    # balances differ between systems — that's a real discrepancy
    # the analyst should see.
    for ai_k, sf_k in asset_fuzzy_pairs:
        agreements += 1
        ai_rec = ai_keys[ai_k]
        sf_rec = sf_keys[sf_k][0]
        ai_src = ai_rec.get("sourceName") or "(unnamed)"
        sf_src = sf_rec.get("Source_Name__c") or "(unnamed)"
        ai_bal = _money(ai_rec.get("currentBalance"))
        sf_bal = _money(
            sf_rec.get("Cash_Value__c") or sf_rec.get("VOA_Current__c")
        )

        # Determine the right phrasing
        if ai_src.lower() != sf_src.lower():
            name_msg = (
                f"Asset name variant — AI: '{ai_src}' vs "
                f"MuleSoft: '{sf_src}' (likely same asset)"
            )
        else:
            name_msg = None  # only case differs — don't bother flagging

        balance_diff = (
            ai_bal is not None and sf_bal is not None
            and not _close(ai_bal, sf_bal, tolerance=0.02)
        )

        if balance_diff:
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity="medium",
                message=(
                    f"ASSET BALANCE MISMATCH — '{sf_src}' "
                    f"({sf_rec.get('Account_Type__c') or ai_rec.get('accountType')}): "
                    f"AI ${ai_bal:,.2f} vs MuleSoft ${sf_bal:,.2f}"
                ),
            ))
        elif name_msg:
            findings.append(Finding(
                category=VALUE_MISMATCH,
                severity="low",
                message=name_msg,
            ))

    for k in ai_only:
        rec = ai_keys[k]
        findings.append(Finding(
            category=MISSING_ASSET,
            severity="high",
            message=(
                f"MuleSoft missing asset — '{rec.get('sourceName')}' "
                f"({rec.get('accountType')}) ${_money(rec.get('currentBalance')) or 0:,.2f}"
            ),
        ))

    for k in sf_only:
        findings.append(Finding(
            category=IDP_MISSED_ASSET,
            severity="medium",
            message=(
                f"AI may have missed asset — '{sf_keys[k][0].get('Source_Name__c')}' "
                f"is in MuleSoft"
            ),
        ))

    return findings, {
        "agreements": agreements,
        "disagreements": disagreements,
        "ai_only": len(ai_only),
        "sf_only": len(sf_only),
    }


# ---------------------------------------------------------------------------
# Compliance findings (IDP-internal — no MuleSoft comparison needed)
# ---------------------------------------------------------------------------

def _classify_idp_finding(msg: str) -> tuple[str, str]:
    """Categorize and assign severity to a raw IDP finding string.

    The IDP pipeline produces strings in a few patterns:
      "[RED] X → field: Not extracted"          → field quality, high
      "[YELLOW] X → field: Not found ..."       → field quality, medium
      "Income discrepancy ... 92% difference"   → internal mismatch, medium
      "Income total mismatch: ..."              → internal mismatch, medium
      "... must be signed (Section 11)"         → compliance, high
      "Missing required compliance document"    → compliance, high
      "Pages 7: ... excluded"                   → extraction note, info
      "Name variants detected ..."              → extraction note, info
    Returns (category, severity).
    """
    lowered = msg.lower()

    if msg.startswith("[RED]"):
        return (FIELD_QUALITY, "high")
    if msg.startswith("[YELLOW]"):
        return (FIELD_QUALITY, "medium")

    if "discrepancy" in lowered or "mismatch" in lowered:
        return (INTERNAL_DISCREPANCY, "medium")

    if (
        "must be signed" in lowered
        or "missing required" in lowered
        or "resubmission required" in lowered
        or "certification requires" in lowered
        or "0 signed of" in lowered
    ):
        return (COMPLIANCE, "high")

    if "review" in lowered or "verify" in lowered:
        return (COMPLIANCE, "medium")

    if "excluded" in lowered or "name variants detected" in lowered:
        return (EXTRACTION_NOTE, "info")

    if "homeless" in lowered or "overpayment" in lowered:
        return (COMPLIANCE, "high")

    return (EXTRACTION_NOTE, "low")


def _idp_internal_findings(extraction: dict) -> list[Finding]:
    """Pull all findings produced by the IDP pipeline itself.

    Includes compliance, cross-doc validation, special scenarios, bug
    detection, cert type rules, and field-level scoring — basically
    everything the IDP pipeline writes into `extraction.findings`.

    These are NOT comparison findings (those come from _compare_*).
    """
    findings: list[Finding] = []
    seen_messages: set[str] = set()

    raw_findings = extraction.get("findings") or []
    for msg in raw_findings:
        if not msg or not isinstance(msg, str):
            continue
        msg_clean = msg.strip()
        if not msg_clean:
            continue
        # Dedup identical strings
        if msg_clean in seen_messages:
            continue
        seen_messages.add(msg_clean)

        category, severity = _classify_idp_finding(msg_clean)
        findings.append(Finding(
            category=category,
            severity=severity,
            message=msg_clean,
        ))

    # Belt-and-suspenders: also flag unsigned TIC if the IDP findings
    # list didn't include it but the cert_info says isSigned=No.
    cert = extraction.get("certification_info") or {}
    if str(cert.get("isSigned") or "").lower() == "no":
        unsigned_msg = "UNSIGNED TIC — TIC form not signed. Resubmission required."
        if unsigned_msg not in seen_messages and not any(
            "not signed" in f.message.lower() for f in findings
        ):
            findings.append(Finding(
                category=COMPLIANCE,
                severity="high",
                message=unsigned_msg,
            ))

    return findings


# ---------------------------------------------------------------------------
# Confidence score
# ---------------------------------------------------------------------------

def _calculate_confidence(
    extraction: dict,
    member_stats: dict, income_stats: dict, asset_stats: dict,
) -> Confidence:
    field_scores = extraction.get("field_scores") or {}
    extraction_score = float(field_scores.get("overall_composite") or 0.0)

    agreements = (member_stats["agreements"] + income_stats["agreements"]
                  + asset_stats["agreements"])
    disagreements = (member_stats["disagreements"] + income_stats["disagreements"]
                     + asset_stats["disagreements"])
    ai_only = (member_stats["ai_only"] + income_stats["ai_only"]
               + asset_stats["ai_only"])
    sf_only = (member_stats["sf_only"] + income_stats["sf_only"]
               + asset_stats["sf_only"])

    # Don't penalize "AI catches MuleSoft miss"; do penalize disagreements
    # and "AI missed something MuleSoft has".
    weight = agreements + disagreements + (sf_only * 0.5)
    if weight > 0:
        rate = (agreements - 0.5 * sf_only) / weight
        agreement_rate = max(0.0, min(1.0, rate))
    else:
        # No comparable records (MuleSoft has nothing) — confidence
        # rests on extraction quality alone.
        agreement_rate = 1.0 if ai_only > 0 else 0.5

    case_confidence = (extraction_score * 0.6) + (agreement_rate * 0.4)
    flag = ("green" if case_confidence >= 0.85
            else "yellow" if case_confidence >= 0.65
            else "red")

    return Confidence(
        extraction_score=extraction_score,
        agreement_rate=agreement_rate,
        case_confidence=case_confidence,
        flag=flag,
        agreements=agreements,
        disagreements=disagreements,
        ai_only_records=ai_only,
        sf_only_records=sf_only,
    )


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def compare(extraction: dict, sf_data: dict) -> ComparisonResult:
    """Diff IDP extraction against MuleSoft data; return findings + score."""
    ai_members = (extraction.get("household_demographics") or {}).get("houseHold") or []
    ai_income = ((extraction.get("income") or {}).get("sourceIncome") or {}).get("verificationIncome") or []
    ai_calculations = extraction.get("income_calculations") or []
    ai_assets = (extraction.get("assets") or {}).get("assetInformation") or []

    sf_members = sf_data.get("members") or []
    sf_income = sf_data.get("income") or []
    sf_assets = sf_data.get("assets") or []

    member_findings, member_stats = _compare_members(ai_members, sf_members)
    income_findings, income_stats = _compare_income(ai_income, ai_calculations, sf_income)
    asset_findings, asset_stats = _compare_assets(ai_assets, sf_assets)
    idp_findings = _idp_internal_findings(extraction)

    findings = (
        member_findings + income_findings + asset_findings + idp_findings
    )
    confidence = _calculate_confidence(
        extraction, member_stats, income_stats, asset_stats,
    )

    return ComparisonResult(findings=findings, confidence=confidence)
